---
abstract: Translating an HTTP Query into SQL::Abstract structure
author:
  - 'Laurent Dami <laurent.dami AT justice.ge.ch>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract-FromQuery
provides:
  SQL::Abstract::FromQuery:
    file: lib/SQL/Abstract/FromQuery.pm
    version: 0.02
  SQL::Abstract::FromQuery::Contains:
    file: lib/SQL/Abstract/FromQuery/Contains.pm
    version: 0
  SQL::Abstract::FromQuery::FR:
    file: lib/SQL/Abstract/FromQuery/FR.pm
    version: 0
  SQL::Abstract::FromQuery::Oracle:
    file: lib/SQL/Abstract/FromQuery/Oracle.pm
    version: 0
requires:
  Module::Load: 0
  Params::Validate: 0
  Regexp::Grammars: 0
  Scalar::Util: 0
  UNIVERSAL::DOES: 0
  namespace::clean: 0
  parent: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
